# fly.toml app configuration file generated for little-shape-7597 on 2023-06-17T10:51:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "little-shape-7597"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
